/**
 * ==========================================================================
 * Sigma Web Development Course - Video 126
 * Topic: Next.js Middleware
 * File: layout.js
 * 
 * Description:
 *   Intercepting requests, checking cookies, and handling redirects or authentication with middleware.js.
 * ==========================================================================
 */
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
