/**
 * ==========================================================================
 * Sigma Web Development Course - Video 128
 * Topic: Layouts, Templates & Nested Routes
 * File: layout.js
 * 
 * Description:
 *   Structuring shared UI layouts, navigation headers, and metadata across nested routes in Next.js.
 * ==========================================================================
 */
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
