/**
 * ==========================================================================
 * Sigma Web Development Course - Video 122
 * Topic: Server vs Client Components in Next.js
 * File: layout.js
 * 
 * Description:
 *   Understanding the boundary between React Server Components ('use client' directive) and Client Components.
 * ==========================================================================
 */
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
