/**
 * ==========================================================================
 * Sigma Web Development Course - Video 127
 * Topic: Authentication with NextAuth / Auth.js
 * File: layout.js
 * 
 * Description:
 *   Implementing secure OAuth (GitHub, Google) and session management in Next.js applications.
 * ==========================================================================
 */
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./component/SessionWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>
      <body className={inter.className}>{children}</body>
      </SessionWrapper>
    </html>
  );
}
