/**
 * ==========================================================================
 * Sigma Web Development Course - Video 124
 * Topic: API Route Handlers in Next.js
 * File: layout.js
 * 
 * Description:
 *   Creating backend REST API endpoints using route.js files with GET, POST, PUT, DELETE handlers.
 * ==========================================================================
 */
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
