/**
 * ==========================================================================
 * Sigma Web Development Course - Video 134
 * Topic: Environment Variables in Next.js
 * File: layout.js
 * 
 * Description:
 *   Configuring .env.local, NEXT_PUBLIC_ client-exposed variables, and private server variables.
 * ==========================================================================
 */
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
